apiVersion: v1
kind: Service
metadata:
  name: matrixos-layer0-service
  labels:
    app: matrixos-layer0
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: matrixos-layer0 